### ISSUE TITLE
IceNet jar file support?

### ISSUE THREAD

**Issue by cokeby190** [anton46/IceNet#1]
Hi!

I think IceNet seems really awesome but I have some projects still stuck in Eclipse and due to certain circumstances I can't migrate them to Android Studio, and thus can't try out your awesome library. ):

It is possible to provide a jar file so at least I can add it to my project in Eclipse? 

If its possible it would be really really awesome!

Thanks!

**Comment by anton46** [comment]
Hi!  

I’ve just add jar file into repo and thanks for appreciation. :)

https://github.com/anton19/IceNet/tree/master/jar

Regards.  

Anton Nurdin Tuhadiansyah
email: anton@icehousecorp.com (mailto:anton@icehousecorp.com) - work: +62 21 573 6225
skype: anton.nurdin - mobile: +62 811 2203 877
Get inspired: www.anton46.com (http://anton46.com/) - facebook (https://www.facebook.com/an.tuhadiansyah) - twitter (https://twitter.com/an_tuhadiansyah) - linkedin (http://id.linkedin.com/pub/anton-nurdin-tuhadiansyah/7a/327/b3a/)

Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by cokeby190** [comment]
Thank youuuuu~ (:
